server:
  port: 7001
  
spring:
  application:
    name:  myEurekaServer
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /home/mySpringCloud/config/
        git:
          uri: https://github.com/SrickySu/myConfigCenter.git #GitHub上面的git仓库名字
          username: 
          password: 

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
          