spring:
  application:
    name: myweb
    
server:
  port: 8081
  
eureka:
  instance:
    instance-id: myweb_instance
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/  